feat(PT-13111): Add plugin workflow
shopware5/SwagEssentials pull request #2
Opened 2023-06-22 13:06 UTC by rathmerdominik

2023-06-22 13:22 UTC, mitelg requested changes
why are the checks not running already?

2023-06-22 13:22 UTC, mitelg commented on .github/workflows/call-plugin-workflow.yml
> +                    - shopware-version: 'v5.6'
is "v5.6" correct? because this is not a valid tag nor a branch name?

2023-06-22 13:22 UTC, mitelg commented on .github/workflows/call-plugin-workflow.yml
> +            - master
would you mind changing this already to "main"? so we do not need to do another PR to change it, once the repo is moved

2023-06-22 13:47 UTC, rathmerdominik commented
> 
@mitelg 

Good question. Maybe there is one initial workflow required?

2023-06-22 14:19 UTC, rathmerdominik commented
> how did you do this in the past?
As far as I remember, there was already a workflow file present and I refactored them...
I am also not sure why it does not run them right now. Maybe there needs to be at least one intial github workflow so that github action detects that we want it enabled for this repository

The "Actions" tab also does not give me the option to choose my PR to start a workflow

2023-06-23 06:32 UTC, mitelg approved these changes
okay, let's merge and see what happens :grin:

2023-07-05 07:50 UTC, rathmerdominik commented
> okay, let's merge and see what happens 😁

Maybe we should not merge it so fast
I have seen some other stuff in the gitlab ci that will be harder to implement
The "Parallel Unit" task for example

2023-07-05 09:17 UTC, mitelg commented
won't do, can be closed

2023-07-05 12:55 UTC, closed without merging